const env = require("dotenv").config();
const express = require("express");
const cookieParser = require("cookie-parser");
const bodyParser = require("body-parser");
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();
const app = express();
const path = require("path");
const cors = require("cors");
const cron = require("node-cron");

const PORT = process.env.PORT || 3550;

const { logger } = require("./middleware/logEvents");
const errorHandler = require("./middleware/errorHandler");
const verifyJWT = require('./middleware/verifyJWT');
const { limiter, authLimiter } = require('./middleware/rateLimiter');
const sanitizeInput = require('./middleware/sanitizeInput');
const imageRoutes = require("./routes/imagesRoute");
const {
  processMonthlyAutoGenerateds,
  autoUpdatePendingJobOrders,
  processMonthlyOverheads,
} = require("./utils/services/schedulerService");

cron.schedule("* 4 * * *", async () => {
  console.log("Running schedulers every 4 hours...");

  try {
    await processMonthlyAutoGenerateds();
  } catch (err) {
    console.error("AutoGenerated error:", err.message);
  }

  try {
    await autoUpdatePendingJobOrders();
  } catch (err) {
    console.error("JobOrder update error:", err.message);
  }

  try {
    await processMonthlyOverheads();
  } catch (err) {
    console.error("Overhead update error:", err.message);
  }


});

app.use(cookieParser());

const allowedOrigins = [
  "http://localhost:5173",
  "http://127.0.0.1:5173",
  "http://localhost:5174",
  "http://127.0.0.1:5174",
  "http://localhost:5500",
  "http://localhost:3000",
  "http://127.0.0.1:3000",
  "http://127.0.0.1:5500",
  "https://jhorizrodel-aquino.github.io",
  /\.trycloudflare\.com$/,
];

const corsOptions = {
  origin: function (origin, callback) {
    // Allow requests with no origin
    if (!origin) return callback(null, true);

    // Check if origin is allowed
    const isAllowed = allowedOrigins.some((allowed) => {
      if (typeof allowed === "string") return allowed === origin;
      if (allowed instanceof RegExp) return allowed.test(origin);
      return false;
    });

    if (isAllowed) {
      callback(null, true);
    } else {
      console.log(`CORS blocked: ${origin}`);
      callback(new Error("Not allowed by CORS"));
    }
  },
  credentials: true,
  methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"],
  allowedHeaders: ["Content-Type", "Authorization", "X-Requested-With"],
};

// Use the cors package
app.use(cors(corsOptions));

// middleware for log handling
app.use(logger);

// urlencoded date
app.use(express.urlencoded({ extended: false }));

// json middleware for auto parse
app.use(express.json());

app.set("trust proxy", 1);

app.use(limiter);
app.use(sanitizeInput);

app.use('/auth', authLimiter, require('./routes/auth'));
app.use("/refresh", require("./routes/refresh"));
app.use("/logout", require("./routes/logout"));

app.use(express.static(path.join(__dirname, "views")));
app.use("/images", imageRoutes);

app.use(verifyJWT);

app.use("/api/users", require("./routes/api/maintabs/users"));
app.use("/api/dashboard", require("./routes/api/maintabs/dashboard"));
app.use("/api/trucks", require("./routes/api/maintabs/trucks"));
app.use("/api/job-orders", require("./routes/api/maintabs/jobOrders"));
app.use("/api/approval-logs", require("./routes/api/maintabs/approvalLogs"));
app.use("/api/activity-logs", require("./routes/api/maintabs/activityLogs"));
app.use("/api/other-incomes", require("./routes/api/maintabs/otherincomes"));

app.use("/api/branches", require("./routes/api/branches"));
app.use("/api/roles", require("./routes/api/roles"));


// EXPENSES ROUTES
app.use("/api/contractor-pays", require("./routes/api/expenses/contractorPays"));
app.use("/api/employee-pays", require("./routes/api/expenses/employeePays"));
app.use("/api/labors", require("./routes/api/expenses/labors"));
app.use("/api/equipments", require("./routes/api/expenses/equipments"));
app.use("/api/materials", require("./routes/api/expenses/materials"));
app.use("/api/overheads", require("./routes/api/expenses/overheads"));

// ROLES RELATED
app.use("/api/me", require("./routes/api/me"));
app.use("/api/contractors", require("./routes/api/roles/contractors"));
app.use("/api/employees", require("./routes/api/roles/employees"));
app.use("/api/customers", require("./routes/api/roles/customers"));

app.use("/api/online-transactions", require("./routes/api/onlineTransactions"));
app.use("/api/transactions", require("./routes/api/maintabs/transactions"));
app.use("/api/finances", require("./routes/api/maintabs/finances"));

app.use("/api/components", require("./routes/api/payComponents"));



app.all(/^.*$/, (req, res) => {
  res.status(404);
  if (req.accepts("html")) {
    res.sendFile(path.join(__dirname, "views", "404.html"));
  } else if (req.accepts("json")) {
    res.json({ error: "404 Not Found" });
  } else {
    res.type("txt").send("404 Not Found");
  }
});

// middleware for error handling
app.use(errorHandler);


app.listen(PORT, "0.0.0.0", () => {
  console.log(`Server running on port ${PORT}`);
});


