// persistent-scheduler.js
const { CronJob } = require("cron");

// Single instance - no class, just an object
const scheduler = {
  schedules: new Map(),
  job: null,

  init() {
    // Run every day at 00:01 AM to catch day changes
    this.job = new CronJob("1 0 * * *", () => {
      this.checkSchedules();
    });

    this.job.start();
    console.log("Scheduler started - checking daily at 00:01");
  },

  updateSchedules(userData) {
    // Clear existing
    this.schedules.clear();

    // Add new schedules
    userData.forEach((user) => {
      this.schedules.set(user.user_id, user.autoGenerated);
    });

    console.log(`Updated schedules for ${this.schedules.size} users`);
  },

  checkSchedules() {
    const today = new Date().getDate();
    console.log(`Checking schedules for day: ${today}`);

    this.triggerSchedulesForDay(today);
  },

  triggerSchedulesForDay(day) {
    let triggerCount = 0;

    for (const [userId, components] of this.schedules) {
      components.forEach((component) => {
        if (component.schedules.includes(day)) {
          triggerCount++;
          this.triggerComponent(userId, component.component_id, day);
        }
      });
    }

    console.log(`Triggered ${triggerCount} components for day ${day}`);
  },

  triggerComponent(userId, componentId, day) {
    console.log(
      `🎯 SCHEDULER: User ${userId}, Component ${componentId}, Day ${day}`
    );

    // Your business logic here
    this.handleComponentTrigger(userId, componentId, day);
  },

  async handleComponentTrigger(userId, componentId, day) {
    try {
      // Implement your trigger logic:

      // Example 1: Database update
      // await db.components.update({ userId, componentId, lastTriggered: new Date() });

      // Example 2: Send notification
      // await notificationService.send(userId, `Component ${componentId} triggered on day ${day}`);

      // Example 3: Call webhook
      // await axios.post(webhookUrl, { userId, componentId, day });

      console.log(
        `✅ Successfully triggered user ${userId}, component ${componentId}`
      );
    } catch (error) {
      console.error(
        `❌ Failed to trigger user ${userId}, component ${componentId}:`,
        error
      );
    }
  },

  // Get current schedules for debugging
  getSchedules() {
    return Array.from(this.schedules.entries()).map(([userId, components]) => ({
      user_id: userId,
      autoGenerated: components,
    }));
  },

  // Manual trigger for testing
  testTrigger(day = new Date().getDate()) {
    console.log(`🧪 TEST: Manual trigger for day ${day}`);
    this.triggerSchedulesForDay(day);
  },
};

// Initialize immediately
scheduler.init();

// Export the single instance
module.exports = scheduler;
