const scheduler = require("../utils/persistentScheduler");
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

// Update schedules

const updateScheduler = async () => {
  let employee = await prisma.employee.findMany({
    where: { autoGenerated: { not: null } },
    select: { userId: true, autoGenerated: true },
  });

  scheduler.updateSchedules(employee);
};

module.exports = updateScheduler;

