const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();
const bcrypt = require("bcrypt");
const fs = require("fs");
const path = require("path");
const { getDateRangeFilter } = require("../../../utils/filters/dateRangeFilter");
const getMainBaseRole = require("../../../utils/services/getMainBaseRole.js");
const checkCustomerRole = require("../../../utils/services/checkCustomerRole.js");
const parseArrayFields = require("../../../utils/services/parseArrayFields.js");
const deleteFile = require("../../../utils/services/imageDeleter.js");
const { requestApproval } = require("../../../utils/services/approvalService");
const { branchFilter } = require("../../../utils/filters/branchFilter");
const checkPendingApproval = require("../../../utils/services/checkPendingApproval")
const relationsChecker = require("../../../utils/services/relationsChecker");
const { logActivity } = require("../../../utils/services/activityService.js");
const updateScheduler = require("../../../middleware/updateSchedule.js")




// GET /
const createUserOld = async (req, res) => {
  const parsedBody = parseArrayFields(req.body, ["roles", "branches"]);
  const {
    name,
    username,
    phone,
    email,
    password,
    description,
    roles,
    branches,
  } = parsedBody;
  const image = req.file ? req.file.filename : null;

  if (!name || !username || !phone || !roles) {
    return res.status(400).json({
      message: "Name, username, phone, branches, and roles are required",
    });
  }

  const hasCustomerRole = await checkCustomerRole(prisma, roles);

  if (!hasCustomerRole && (!branches || branches.length === 0)) {
    return res
      .status(400)
      .json({ message: "Branches are required for non-customer users" });
  }

  const existingUser = await prisma.user.findFirst({
    where: {
      status: "active",
      OR: [
        { username },
        ...(email ? [{ email }] : []),
      ],
    },
  });

  const pendingUsername = await checkPendingApproval(prisma, 'user', ['username'], username);
  const pendingEmail = await checkPendingApproval(prisma, 'user', ['email'], email);

  if (existingUser || pendingUsername || pendingEmail) {
    let message = [];
    if (
      (existingUser && existingUser.username === username) ||
      (pendingUsername && pendingUsername.value === username)
    )
      message.push("Username");
    if (
      (existingUser && existingUser.email === email) ||
      (pendingEmail && pendingEmail.value === email)
    )
      message.push("Email");

    return res
      .status(400)
      .json({ message: `${message.join(" and ")} already exist` });
  }

  try {
    const needsApproval = req.approval;
    const message = needsApproval
      ? "User created is awaiting approval"
      : "User is successfully created";

    const hashPwd = await bcrypt.hash(password || process.env.DEFAULT_PASSWORD, 10);
    const userData = {
      fullName: name,
      username,
      phone: phone.toString(),
      ...(email ? { email } : {}),
      hashPwd,
      ...(description ? { description } : {}),
      createdByUser: req.username || null,
      updatedByUser: req.username || null,
      ...(needsApproval ? { roles, branches } : {}),
      image
    };

    const result = await prisma.$transaction(async (tx) => {
      const user = needsApproval
        ? await requestApproval('user', null, 'create', userData, req.username)
        : await tx.user.create({ data: { ...userData, status: "active" } });

      if (!needsApproval) {
        const roleTableMap = {
          admin: () => tx.admin.create({ data: { userId: user.id } }),
          customer: () => tx.customer.create({ data: { userId: user.id } }),
          employee: () => {
            const autoGenerated = req.body.autoGenerated;

            return tx.employee.create({ data: { userId: user.id, autoGenerated } });
            }, 
          contractor: () => {
            const commission = Number(req.body.commission);

            if (!commission) {
              return res.status(400).json({ message: "Commission is required"})
            }

            if (isNaN(commission)) {
              return res.status(400).json({ message: "Commission must be a valid number"})
            }

            if (commission > 1) {
              return res.status(400).json({ message: "Commission cannot be higher than 1 (100%)"})
            }

            if (commission < 0) {
              return res.status(400).json({ message: "Commission cannot be negative"})
            }

            return tx.contractor.create({
              data: { userId: user.id, commission },
            });
          },
        };


        // Fetch role IDs for this user
        const roleNamesToCreateTables = await Promise.all(
          roles.map((rId) => getMainBaseRole(tx, rId))
        );

        // Remove duplicates and nulls
        const uniqueRoleNames = [...new Set(roleNamesToCreateTables.filter(Boolean))];

        // Create tables for main roles
        await Promise.all(uniqueRoleNames.map((roleName) => roleTableMap[roleName]()));
        updateScheduler();
      }

      // userRole table
      const userRoleData = roles.map((role) => ({ roleId: role, userId: user.id }));
      if (!needsApproval) await tx.userRole.createMany({ data: userRoleData });

      // userBranch table
      const userBranchData =
        branches?.length > 0
          ? branches.map((branch) => ({ branchId: branch, userId: user.id }))
          : [];

      if (!needsApproval && userBranchData.length > 0) {
        await tx.userBranch.createMany({ data: userBranchData });
      }

      const userDetails = await tx.user.findFirst({
        where: { id: user.id },
      });

      return { user, userDetails } ;
    });

    await logActivity(
      req.username,
      needsApproval
        ? `FOR APPROVAL: ${req.username} created User ${username}`
        : `${req.username} created User ${username}`,
    );

    return res.status(201).json({
      message,
      data: needsApproval ? { approvalId: result.user.id, username: result.user.payload.username, fullName: result.user.payload.fullName } : { userId: result.userDetails.id, username: result.userDetails.username,  fullName: result.userDetails.fullName } ,
    });
  } catch (err) {
    console.log(err.message)
    return res.status(500).json({ error: err.message });
  }
};

const createUser = async (req, res) => {
  const parsedBody = parseArrayFields(req.body, ["roles", "branches"]);
  const {
    name,
    username,
    phone,
    email,
    password,
    description,
    roles,
    branches,
    commission,
    autoGenerated, // Add autoGenerated here for employee role
  } = parsedBody;
  const image = req.file ? req.file.filename : null;

  if (!name || !username || !phone || !roles) {
    return res.status(400).json({
      message: "Name, username, phone, and roles are required",
    });
  }

  try {
    // Pre-fetch all role base names for validation
    const roleBaseNames = await Promise.all(
      roles.map((roleId) => getMainBaseRole(prisma, roleId))
    );

    const isContractor = roleBaseNames.some(
      (roleName) => roleName === "contractor"
    );
    const isEmployee = roleBaseNames.some(
      (roleName) => roleName === "employee"
    );
    const hasCustomerRole = roleBaseNames.some(
      (roleName) => roleName === "customer"
    );

    // Validate commission if contractor role is selected
    if (isContractor) {
      const commissionValue = Number(commission);

      if (!commission && commission !== 0) {
        return res
          .status(400)
          .json({ message: "Commission is required for contractor" });
      }

      if (isNaN(commissionValue)) {
        return res
          .status(400)
          .json({ message: "Commission must be a valid number" });
      }

      if (commissionValue > 1) {
        return res
          .status(400)
          .json({ message: "Commission cannot be higher than 1 (100%)" });
      }

      if (commissionValue < 0) {
        return res
          .status(400)
          .json({ message: "Commission cannot be negative" });
      }
    }

    // Validate autoGenerated if employee role is selected
    if (isEmployee) {
      if (!autoGenerated) {
        return res
          .status(400)
          .json({ message: "autoGenerated is required for employee role" });
      }

      // Validate that autoGenerated is a valid JSON object/array
      try {
        let parsedAutoGenerated = autoGenerated;

        // If it's a string, try to parse it
        if (typeof autoGenerated === "string") {
          parsedAutoGenerated = JSON.parse(autoGenerated);
        }

        // Check if it's an array (based on your expected structure)
        if (!Array.isArray(parsedAutoGenerated)) {
          return res
            .status(400)
            .json({ message: "autoGenerated must be a valid JSON array" });
        }

        // Validate each item in the array has required fields
        const isValidStructure = parsedAutoGenerated.every(
          (item) =>
            item &&
            typeof item === "object" &&
            item.component_id &&
            item.schedules &&
            Array.isArray(item.schedules)
        );

        if (!isValidStructure) {
          return res.status(400).json({
            message:
              "autoGenerated must contain objects with 'component_id' and 'schedules' array",
          });
        }
      } catch (error) {
        return res
          .status(400)
          .json({ message: "autoGenerated must be a valid JSON format" });
      }
    }

    if (!hasCustomerRole && (!branches || branches.length === 0)) {
      return res
        .status(400)
        .json({ message: "Branches are required for non-customer users" });
    }

    const existingUser = await prisma.user.findFirst({
      where: {
        status: "active",
        OR: [{ username }, ...(email ? [{ email }] : [])],
      },
    });

    const pendingUsername = await checkPendingApproval(
      prisma,
      "user",
      ["username"],
      username
    );
    const pendingEmail = await checkPendingApproval(
      prisma,
      "user",
      ["email"],
      email
    );

    if (existingUser || pendingUsername || pendingEmail) {
      let message = [];
      if (
        (existingUser && existingUser.username === username) ||
        (pendingUsername && pendingUsername.value === username)
      )
        message.push("Username");
      if (
        (existingUser && existingUser.email === email) ||
        (pendingEmail && pendingEmail.value === email)
      )
        message.push("Email");

      return res
        .status(400)
        .json({ message: `${message.join(" and ")} already exist` });
    }

    const needsApproval = true;
    const message = needsApproval
      ? "User created is awaiting approval"
      : "User is successfully created";

    const hashPwd = await bcrypt.hash(
      password || process.env.DEFAULT_PASSWORD,
      10
    );

    // Process autoGenerated for storage (keep as JSON, no string conversion needed)
    let processedAutoGenerated = null;
    if (isEmployee && autoGenerated) {
      // If it's a string, parse it to ensure it's a proper JSON object
      processedAutoGenerated =
        typeof autoGenerated === "string"
          ? JSON.parse(autoGenerated)
          : autoGenerated;
    }

    // Include commission and autoGenerated in userData for both approval and direct creation
    const userData = {
      fullName: name,
      username,
      phone: phone.toString(),
      ...(email ? { email } : {}),
      hashPwd,
      ...(description ? { description } : {}),
      createdByUser: req.username || null,
      updatedByUser: req.username || null,
      ...(needsApproval
        ? {
            roles,
            branches,
            ...(isContractor && { commission: Number(commission) }), // Include commission only if contractor
            ...(isEmployee && { autoGenerated: processedAutoGenerated }), // Include autoGenerated only if employee
          }
        : {}),
      image,
    };

    const result = await prisma.$transaction(async (tx) => {
      const user = needsApproval
        ? await requestApproval("user", null, "create", userData, req.username)
        : await tx.user.create({ data: { ...userData, status: "active" } });

      if (!needsApproval) {
        const roleTableMap = {
          admin: () => tx.admin.create({ data: { userId: user.id } }),
          customer: () => tx.customer.create({ data: { userId: user.id } }),
          employee: () => {
            // Store autoGenerated directly as JSON (Prisma will handle it)
            return tx.employee.create({
              data: {
                userId: user.id,
                autoGenerated: processedAutoGenerated,
              },
            });
          },
          contractor: () => {
            const commissionValue = Number(commission);
            return tx.contractor.create({
              data: { userId: user.id, commission: commissionValue },
            });
          },
        };

        // Use the pre-fetched roleBaseNames instead of calling getMainBaseRole again
        const uniqueRoleNames = [...new Set(roleBaseNames.filter(Boolean))];

        // Create tables for main roles
        await Promise.all(
          uniqueRoleNames.map((roleName) => roleTableMap[roleName]())
        );

        // userRole table
        const userRoleData = roles.map((role) => ({
          roleId: role,
          userId: user.id,
        }));
        await tx.userRole.createMany({ data: userRoleData });

        // userBranch table
        const userBranchData =
          branches?.length > 0
            ? branches.map((branch) => ({ branchId: branch, userId: user.id }))
            : [];

        if (userBranchData.length > 0) {
          await tx.userBranch.createMany({ data: userBranchData });
        }
      }

      const userDetails = await tx.user.findFirst({
        where: { id: user.id },
      });

      return { user, userDetails };
    });

    await logActivity(
      req.username,
      needsApproval
        ? `FOR APPROVAL: ${req.username} created User ${username}`
        : `${req.username} created User ${username}`
    );

    // Update scheduler with the new employee's autoGenerated data
    if (isEmployee && !needsApproval && processedAutoGenerated) {
      updateScheduler();
    }

    return res.status(201).json({
      message,
      data: needsApproval
        ? {
            username: result.user.payload.username,
            fullName: result.user.payload.fullName,
            ...(isContractor && { commission: Number(commission) }), // Include commission in response if contractor
            ...(isEmployee && { autoGenerated: processedAutoGenerated }), // Include autoGenerated in response if employee
          }
        : {
            userId: result.userDetails.id,
            username: result.userDetails.username,
            fullName: result.userDetails.fullName,
            ...(isEmployee && { autoGenerated: processedAutoGenerated }), // Include autoGenerated in direct creation response too
          },
    });
  } catch (err) {
    console.log(err.message);
    return res.status(500).json({ error: err.message });
  }
};

// PUT /:id
const editUserOld = async (req, res) => {
  const parsedBody = parseArrayFields(req.body, ["roles", "branches"]);
  const { name, phone, email, description, roles, branches, remarks } = parsedBody;
  const newImage = req.file ? req.file.filename : null;

  if (!req?.params?.id)
    return res.status(400).json({ message: "ID is required" });

  const user = await prisma.user.findFirst({ where: { id: req.params.id } });
  if (!user)
    return res
      .status(400)
      .json({ message: `User with ${req.params.id} doesn't exist` });

  try {
    let needsApproval = req.approval;
    let message = needsApproval
        ? "User edit awaiting approval"
        : "User edited successfully";
    
    if (roles) {
      const hasCustomerRole = await checkCustomerRole(prisma, roles);

      if (!hasCustomerRole && (!branches || branches.length === 0)) {
        return res
          .status(400)
          .json({ message: "Branches are required for non-customer users" });
      }
    }

    if (email && email !== user.email) {
      const existingUser = await prisma.user.findFirst({ where: { email, status:  "active", id: { not: req.params.id } } });
      const pendingUser = await checkPendingApproval(prisma, 'user', ['email'], email, req.params.id);
      const pendingJobOrderUser = await checkPendingApproval(prisma, 'jobOrder', ['customerData', 'email'], email, req.params.id);

      if (existingUser || pendingUser || pendingJobOrderUser) {
      return res
        .status(400)
        .json({ message: "Email already in use or pending approval" });
      }
    }

    let image = newImage ? newImage : user.image;

    if (!needsApproval) {
      if (newImage) {
        if (user.image) {
          deleteFile(`images/${user.image}`);
        }
        image = newImage;
      }
      // If frontend sent image: null or empty string → remove old image
      else if ((req.body.image === null || req.body.image === "") && user.image) {
        deleteFile(`images/${user.image}`);
        image = null;
      }
    }

    const updatedData = {
      fullName: name ?? user.fullName,
      username: user.username,
      phone: phone ?? user.phone,
      email: email ?? user.email,
      hashPwd: user.hashPwd,
      description: description ?? user.description,
      image,
      updatedByUser: req.username,
      ...(needsApproval ? { roles, branches } : {}),
    };

    const result = await prisma.$transaction(async (tx) => {
      const editedUser = needsApproval
        ? await requestApproval('user', req.params.id, 'edit', {
              ...updatedData,
              createdByUser: req.username }, req.username)
        : await tx.user.update({
            where: { id: user.id },
            data: updatedData,
          });

      const arraysEqual = (a, b) =>
        Array.isArray(a) &&
        Array.isArray(b) &&
        a.length === b.length &&
        [...a].sort().join(",") === [...b].sort().join(",");

      if (!needsApproval && roles && !arraysEqual(user.roles, roles)) {
        // STEP 1: Reset junction table roles
        await tx.userRole.deleteMany({ where: { userId: user.id } });

        await tx.userRole.createMany({
          data: roles.map((role) => ({ userId: user.id, roleId: role })),
        });

        // STEP 2: Clear old role-specific tables
        await Promise.all([
          tx.admin.deleteMany({ where: { userId: user.id } }),
          tx.customer.deleteMany({ where: { userId: user.id } }),
          tx.employee.deleteMany({ where: { userId: user.id } }),
          tx.contractor.deleteMany({ where: { userId: user.id } }),
        ]);

        // STEP 3: Recreate tables based on main roles (recursive)
        const roleTableMap = {
          admin: () => tx.admin.create({ data: { userId: user.id } }),
          customer: () => tx.customer.create({ data: { userId: user.id } }),
          employee: () => tx.employee.create({ data: { userId: user.id } }),
          contractor: () => {
            const commission = Number(req.body.commission);

            if (!commission) {
              return res.status(400).json({ message: "Commission is required"})
            }
            
            if (isNaN(commission)) {
              return res.status(400).json({ message: "Commission must be a valid number"})
            }

            if (commission > 1) {
              return res.status(400).json({ message: "Commission cannot be higher than 1 (100%)"})
            }

            if (commission < 0) {
              return res.status(400).json({ message: "Commission cannot be negative"})
            }

            return tx.contractor.create({
              data: { userId: user.id, commission },
            });
          },
        };

        // Determine main roles from roleIds recursively
        const roleNamesToCreateTables = await Promise.all(
          roles.map((roleId) => getMainBaseRole(prisma, roleId))
        );

        const uniqueRoleNames = [...new Set(roleNamesToCreateTables)].filter(Boolean);

        // Run mapped role table functions for main roles
        await Promise.all(
          uniqueRoleNames
            .filter((roleName) => roleTableMap[roleName])
            .map((roleName) => roleTableMap[roleName]())
        );
      }

      // STEP 4: Update branches if changed
      if (!needsApproval && branches && !arraysEqual(user.branches, branches)) {
        await tx.userBranch.deleteMany({ where: { userId: user.id } });
        await tx.userBranch.createMany({
          data: branches.map((branch) => ({ userId: user.id, branchId: branch })),
        });
      }

      const userDetails = await tx.user.findFirst({
        where: { id: editedUser.id },
        include: {
          roles: { include: { role: true } },
          branches: { include: { branch: true } },
        },
      });

      return { userDetails, user };
    });

    let safeUser;
    if (!needsApproval) {
      const { hashPwd: _, refreshToken, ...rest } = result.userDetails;
      safeUser = rest;
    };

    await logActivity(
      req.username,
      needsApproval
        ? `FOR APPROVAL: ${req.username} edited User ${updatedData.username}`
        : `${req.username} edited User ${updatedData.username}`,
        remarks
    );

    return res.status(201).json({
      message,
      data: needsApproval ? result.user : safeUser,
    });
  } catch (err) {
    console.log(err.message)
    return res.status(500).json({ error: err.message });
  }
};

const editUserNew = async (req, res) => {
  const parsedBody = parseArrayFields(req.body, ["roles", "branches"]);
  const {
    name,
    phone,
    email,
    description,
    roles,
    branches,
    remarks,
    commission,
  } = parsedBody;
  const newImage = req.file ? req.file.filename : null;

  if (!req?.params?.id)
    return res.status(400).json({ message: "ID is required" });

  const user = await prisma.user.findFirst({
    where: { id: req.params.id },
    include: {
      roles: { include: { role: true } },
      contractor: true,
    },
  });

  if (!user)
    return res
      .status(400)
      .json({ message: `User with ${req.params.id} doesn't exist` });

  try {
    let needsApproval = req.approval;
    let message = needsApproval
      ? "User edit awaiting approval"
      : "User edited successfully";

    // Get current role IDs for comparison
    const currentRoleIds = user.roles.map((role) => role.roleId);

    if (roles) {
      const hasCustomerRole = await checkCustomerRole(prisma, roles);

      if (!hasCustomerRole && (!branches || branches.length === 0)) {
        return res
          .status(400)
          .json({ message: "Branches are required for non-customer users" });
      }
    }

    if (email && email !== user.email) {
      const existingUser = await prisma.user.findFirst({
        where: { email, status: "active", id: { not: req.params.id } },
      });
      const pendingUser = await checkPendingApproval(
        prisma,
        "user",
        ["email"],
        email,
        req.params.id
      );
      const pendingJobOrderUser = await checkPendingApproval(
        prisma,
        "jobOrder",
        ["customerData", "email"],
        email,
        req.params.id
      );

      if (existingUser || pendingUser || pendingJobOrderUser) {
        return res
          .status(400)
          .json({ message: "Email already in use or pending approval" });
      }
    }

    let image = newImage ? newImage : user.image;

    if (!needsApproval) {
      if (newImage) {
        if (user.image) {
          deleteFile(`images/${user.image}`);
        }
        image = newImage;
      }
      // If frontend sent image: null or empty string → remove old image
      else if (
        (req.body.image === null || req.body.image === "") &&
        user.image
      ) {
        deleteFile(`images/${user.image}`);
        image = null;
      }
    }

    const updatedData = {
      fullName: name ?? user.fullName,
      username: user.username,
      phone: phone ?? user.phone,
      email: email ?? user.email,
      hashPwd: user.hashPwd,
      description: description ?? user.description,
      image,
      updatedByUser: req.username,
      ...(needsApproval ? { roles, branches } : {}),
    };

    const result = await prisma.$transaction(async (tx) => {
      const editedUser = needsApproval
        ? await requestApproval(
            "user",
            req.params.id,
            "edit",
            {
              ...updatedData,
              createdByUser: req.username,
            },
            req.username
          )
        : await tx.user.update({
            where: { id: user.id },
            data: updatedData,
          });

      const arraysEqual = (a, b) =>
        Array.isArray(a) &&
        Array.isArray(b) &&
        a.length === b.length &&
        [...a].sort().join(",") === [...b].sort().join(",");

      // ✅ Check if user is currently a contractor (using base roles)
      const currentBaseRoles = await Promise.all(
        currentRoleIds.map((roleId) => getMainBaseRole(prisma, roleId))
      );
      const isCurrentlyContractor = currentBaseRoles.includes("contractor");

      // ✅ Check if user will be a contractor after role changes
      let willBeContractor = isCurrentlyContractor;
      if (roles && !arraysEqual(currentRoleIds, roles)) {
        const newBaseRoles = await Promise.all(
          roles.map((roleId) => getMainBaseRole(prisma, roleId))
        );
        willBeContractor = newBaseRoles.includes("contractor");
      }

      // ✅ Handle commission updates for contractors
      if (!needsApproval && commission !== undefined) {
        if (willBeContractor) {
          const commissionValue = Number(commission);

          if (isNaN(commissionValue)) {
            throw new Error("Commission must be a valid number");
          }
          if (commissionValue > 1) {
            throw new Error("Commission cannot be higher than 1 (100%)");
          }
          if (commissionValue < 0) {
            throw new Error("Commission cannot be negative");
          }

          // Update or create contractor record
          if (user.contractor) {
            await tx.contractor.update({
              where: { userId: user.id },
              data: { commission: commissionValue },
            });
          } else {
            await tx.contractor.create({
              data: {
                userId: user.id,
                commission: commissionValue,
              },
            });
          }
        } else if (user.contractor) {
          // Remove contractor record if user is no longer a contractor
          await tx.contractor.deleteMany({ where: { userId: user.id } });
        }
      }

      if (!needsApproval && roles && !arraysEqual(currentRoleIds, roles)) {
        // STEP 1: Reset junction table roles
        await tx.userRole.deleteMany({ where: { userId: user.id } });

        await tx.userRole.createMany({
          data: roles.map((role) => ({ userId: user.id, roleId: role })),
        });

        // STEP 2: Clear old role-specific tables
        await Promise.all([
          tx.admin.deleteMany({ where: { userId: user.id } }),
          tx.customer.deleteMany({ where: { userId: user.id } }),
          tx.employee.deleteMany({ where: { userId: user.id } }),
          tx.contractor.deleteMany({ where: { userId: user.id } }),
        ]);

        // STEP 3: Recreate tables based on main roles (using getMainBaseRole)
        const roleTableMap = {
          admin: () => tx.admin.create({ data: { userId: user.id } }),
          customer: () => tx.customer.create({ data: { userId: user.id } }),
          employee: () => {
            const autoGenerated = req.body.autoGenerated;

            return tx.employee.create({
              data: { userId: user.id, autoGenerated },
            });
          },
          contractor: () => {
            const commissionValue = Number(
              commission ?? user.contractor?.commission ?? 0
            );

            if (isNaN(commissionValue)) {
              throw new Error("Commission must be a valid number");
            }
            if (commissionValue > 1) {
              throw new Error("Commission cannot be higher than 1 (100%)");
            }
            if (commissionValue < 0) {
              throw new Error("Commission cannot be negative");
            }

            return tx.contractor.create({
              data: { userId: user.id, commission: commissionValue },
            });
          },
        };

        // Determine main roles from roleIds using getMainBaseRole
        const roleNamesToCreateTables = await Promise.all(
          roles.map((roleId) => getMainBaseRole(prisma, roleId))
        );

        const uniqueRoleNames = [...new Set(roleNamesToCreateTables)].filter(
          Boolean
        );

        // Run mapped role table functions for main roles
        await Promise.all(
          uniqueRoleNames
            .filter((roleName) => roleTableMap[roleName])
            .map((roleName) => roleTableMap[roleName]())
        );
      }

      // STEP 4: Update branches if changed
      if (!needsApproval && branches && !arraysEqual(user.branches, branches)) {
        await tx.userBranch.deleteMany({ where: { userId: user.id } });
        await tx.userBranch.createMany({
          data: branches.map((branch) => ({
            userId: user.id,
            branchId: branch,
          })),
        });
      }

      const userDetails = await tx.user.findFirst({
        where: { id: editedUser.id },
        include: {
          roles: { include: { role: true } },
          branches: { include: { branch: true } },
          contractor: true,
        },
      });

      return { userDetails, user };
    });

    let safeUser;
    if (!needsApproval) {
      const { hashPwd: _, refreshToken, ...rest } = result.userDetails;
      safeUser = rest;
    }

    await logActivity(
      req.username,
      needsApproval
        ? `FOR APPROVAL: ${req.username} edited User ${updatedData.username}`
        : `${req.username} edited User ${updatedData.username}`,
      remarks
    );

    updateScheduler();
    return res.status(201).json({
      message,
      data: needsApproval ? result.user : safeUser,
    });
  } catch (err) {
    console.log(err.message);
    return res.status(500).json({ error: err.message });
  }
};

const editUser = async (req, res) => {
  const parsedBody = parseArrayFields(req.body, ["roles", "branches"]);
  const {
    name,
    phone,
    email,
    description,
    roles,
    branches,
    remarks,
    commission,
    autoGenerated, // Add autoGenerated here
  } = parsedBody;
  const newImage = req.file ? req.file.filename : null;

  if (!req?.params?.id)
    return res.status(400).json({ message: "ID is required" });

  const user = await prisma.user.findFirst({
    where: { id: req.params.id },
    include: {
      roles: { include: { role: true } },
      contractor: true,
      employee: true, // Include employee to check existing autoGenerated
    },
  });

  if (!user)
    return res
      .status(400)
      .json({ message: `User with ${req.params.id} doesn't exist` });

  try {
    let needsApproval = req.approval;
    let message = needsApproval
      ? "User edit awaiting approval"
      : "User edited successfully";

    // Get current role IDs for comparison
    const currentRoleIds = user.roles.map((role) => role.roleId);

    // Pre-fetch role base names for validation
    let roleBaseNames = [];
    if (roles) {
      roleBaseNames = await Promise.all(
        roles.map((roleId) => getMainBaseRole(prisma, roleId))
      );

      const hasCustomerRole = roleBaseNames.includes("customer");
      const isEmployee = roleBaseNames.includes("employee");
      const isContractor = roleBaseNames.includes("contractor");

      if (!hasCustomerRole && (!branches || branches.length === 0)) {
        return res
          .status(400)
          .json({ message: "Branches are required for non-customer users" });
      }

      // Validate commission if contractor role is selected
      if (isContractor) {
        const commissionValue = Number(commission);

        if (commission === undefined || commission === null) {
          return res
            .status(400)
            .json({ message: "Commission is required for contractor" });
        }

        if (isNaN(commissionValue)) {
          return res
            .status(400)
            .json({ message: "Commission must be a valid number" });
        }

        if (commissionValue > 1) {
          return res
            .status(400)
            .json({ message: "Commission cannot be higher than 1 (100%)" });
        }

        if (commissionValue < 0) {
          return res
            .status(400)
            .json({ message: "Commission cannot be negative" });
        }
      }

      // Validate autoGenerated if employee role is selected
      if (isEmployee) {
        if (!autoGenerated && !user.employee?.autoGenerated) {
          return res
            .status(400)
            .json({ message: "autoGenerated is required for employee role" });
        }

        // Validate that autoGenerated is a valid JSON object/array if provided
        if (autoGenerated) {
          try {
            let parsedAutoGenerated = autoGenerated;

            if (typeof autoGenerated === "string") {
              parsedAutoGenerated = JSON.parse(autoGenerated);
            }

            if (!Array.isArray(parsedAutoGenerated)) {
              return res
                .status(400)
                .json({ message: "autoGenerated must be a valid JSON array" });
            }

            const isValidStructure = parsedAutoGenerated.every(
              (item) =>
                item &&
                typeof item === "object" &&
                item.component_id &&
                item.schedules &&
                Array.isArray(item.schedules)
            );

            if (!isValidStructure) {
              return res.status(400).json({
                message:
                  "autoGenerated must contain objects with 'component_id' and 'schedules' array",
              });
            }
          } catch (error) {
            return res
              .status(400)
              .json({ message: "autoGenerated must be a valid JSON format" });
          }
        }
      }
    }

    if (email && email !== user.email) {
      const existingUser = await prisma.user.findFirst({
        where: { email, status: "active", id: { not: req.params.id } },
      });
      const pendingUser = await checkPendingApproval(
        prisma,
        "user",
        ["email"],
        email,
        req.params.id
      );
      const pendingJobOrderUser = await checkPendingApproval(
        prisma,
        "jobOrder",
        ["customerData", "email"],
        email,
        req.params.id
      );

      if (existingUser || pendingUser || pendingJobOrderUser) {
        return res
          .status(400)
          .json({ message: "Email already in use or pending approval" });
      }
    }

    let image = newImage ? newImage : user.image;

    if (!needsApproval) {
      if (newImage) {
        if (user.image) {
          deleteFile(`images/${user.image}`);
        }
        image = newImage;
      }
      // If frontend sent image: null or empty string → remove old image
      else if (
        (req.body.image === null || req.body.image === "") &&
        user.image
      ) {
        deleteFile(`images/${user.image}`);
        image = null;
      }
    }

    // Process autoGenerated for storage
    let processedAutoGenerated = null;
    if (autoGenerated) {
      processedAutoGenerated =
        typeof autoGenerated === "string"
          ? JSON.parse(autoGenerated)
          : autoGenerated;
    }

    const updatedData = {
      fullName: name ?? user.fullName,
      username: user.username,
      phone: phone ?? user.phone,
      email: email ?? user.email,
      hashPwd: user.hashPwd,
      description: description ?? user.description,
      image,
      updatedByUser: req.username,
      ...(needsApproval
        ? {
            roles,
            branches,
            ...(roleBaseNames.includes("contractor") && {
              commission: Number(commission),
            }),
            ...(roleBaseNames.includes("employee") && {
              autoGenerated: processedAutoGenerated,
            }),
          }
        : {}),
    };

    const result = await prisma.$transaction(async (tx) => {
      const editedUser = needsApproval
        ? await requestApproval(
            "user",
            req.params.id,
            "edit",
            {
              ...updatedData,
              createdByUser: req.username,
            },
            req.username
          )
        : await tx.user.update({
            where: { id: user.id },
            data: updatedData,
          });

      const arraysEqual = (a, b) =>
        Array.isArray(a) &&
        Array.isArray(b) &&
        a.length === b.length &&
        [...a].sort().join(",") === [...b].sort().join(",");

      // ✅ Check if user is currently a contractor (using base roles)
      const currentBaseRoles = await Promise.all(
        currentRoleIds.map((roleId) => getMainBaseRole(prisma, roleId))
      );
      const isCurrentlyContractor = currentBaseRoles.includes("contractor");
      const isCurrentlyEmployee = currentBaseRoles.includes("employee");

      // ✅ Check if user will be a contractor/employee after role changes
      let willBeContractor = isCurrentlyContractor;
      let willBeEmployee = isCurrentlyEmployee;
      if (roles && !arraysEqual(currentRoleIds, roles)) {
        const newBaseRoles = await Promise.all(
          roles.map((roleId) => getMainBaseRole(prisma, roleId))
        );
        willBeContractor = newBaseRoles.includes("contractor");
        willBeEmployee = newBaseRoles.includes("employee");
      }

      // ✅ Handle commission and autoGenerated updates for direct edits (no approval needed)
      if (!needsApproval) {
        // Handle commission updates for contractors
        if (commission !== undefined) {
          if (willBeContractor) {
            const commissionValue = Number(commission);

            if (isNaN(commissionValue)) {
              throw new Error("Commission must be a valid number");
            }
            if (commissionValue > 1) {
              throw new Error("Commission cannot be higher than 1 (100%)");
            }
            if (commissionValue < 0) {
              throw new Error("Commission cannot be negative");
            }

            // Update or create contractor record
            if (user.contractor) {
              await tx.contractor.update({
                where: { userId: user.id },
                data: { commission: commissionValue },
              });
            } else {
              await tx.contractor.create({
                data: {
                  userId: user.id,
                  commission: commissionValue,
                },
              });
            }
          } else if (user.contractor) {
            // Remove contractor record if user is no longer a contractor
            await tx.contractor.deleteMany({ where: { userId: user.id } });
          }
        }

        // Handle autoGenerated updates for employees
        if (autoGenerated !== undefined) {
          if (willBeEmployee) {
            // Update or create employee record with autoGenerated
            if (user.employee) {
              await tx.employee.update({
                where: { userId: user.id },
                data: { autoGenerated: processedAutoGenerated },
              });
            } else {
              await tx.employee.create({
                data: {
                  userId: user.id,
                  autoGenerated: processedAutoGenerated,
                },
              });
            }
          } else if (user.employee) {
            // Remove autoGenerated if user is no longer an employee
            await tx.employee.update({
              where: { userId: user.id },
              data: { autoGenerated: null },
            });
          }
        }
      }

      if (!needsApproval && roles && !arraysEqual(currentRoleIds, roles)) {
        // STEP 1: Reset junction table roles
        await tx.userRole.deleteMany({ where: { userId: user.id } });

        await tx.userRole.createMany({
          data: roles.map((role) => ({ userId: user.id, roleId: role })),
        });

        // STEP 2: Clear old role-specific tables
        await Promise.all([
          tx.admin.deleteMany({ where: { userId: user.id } }),
          tx.customer.deleteMany({ where: { userId: user.id } }),
          tx.employee.deleteMany({ where: { userId: user.id } }),
          tx.contractor.deleteMany({ where: { userId: user.id } }),
        ]);

        // STEP 3: Recreate tables based on main roles (using getMainBaseRole)
        const roleTableMap = {
          admin: () => tx.admin.create({ data: { userId: user.id } }),
          customer: () => tx.customer.create({ data: { userId: user.id } }),
          employee: () => {
            // Use processed autoGenerated or existing data
            const finalAutoGenerated =
              processedAutoGenerated || user.employee?.autoGenerated;
            return tx.employee.create({
              data: { userId: user.id, autoGenerated: finalAutoGenerated },
            });
          },
          contractor: () => {
            const commissionValue = Number(
              commission ?? user.contractor?.commission ?? 0
            );

            if (isNaN(commissionValue)) {
              throw new Error("Commission must be a valid number");
            }
            if (commissionValue > 1) {
              throw new Error("Commission cannot be higher than 1 (100%)");
            }
            if (commissionValue < 0) {
              throw new Error("Commission cannot be negative");
            }

            return tx.contractor.create({
              data: { userId: user.id, commission: commissionValue },
            });
          },
        };

        // Determine main roles from roleIds using getMainBaseRole
        const roleNamesToCreateTables = await Promise.all(
          roles.map((roleId) => getMainBaseRole(prisma, roleId))
        );

        const uniqueRoleNames = [...new Set(roleNamesToCreateTables)].filter(
          Boolean
        );

        // Run mapped role table functions for main roles
        await Promise.all(
          uniqueRoleNames
            .filter((roleName) => roleTableMap[roleName])
            .map((roleName) => roleTableMap[roleName]())
        );
      }

      // STEP 4: Update branches if changed
      if (!needsApproval && branches && !arraysEqual(user.branches, branches)) {
        await tx.userBranch.deleteMany({ where: { userId: user.id } });
        await tx.userBranch.createMany({
          data: branches.map((branch) => ({
            userId: user.id,
            branchId: branch,
          })),
        });
      }

      const userDetails = await tx.user.findFirst({
        where: { id: editedUser.id },
        include: {
          roles: { include: { role: true } },
          branches: { include: { branch: true } },
          contractor: true,
          employee: true,
        },
      });

      return { userDetails, user };
    });

    let safeUser;
    if (!needsApproval) {
      const { hashPwd: _, refreshToken, ...rest } = result.userDetails;
      safeUser = rest;
    }

    await logActivity(
      req.username,
      needsApproval
        ? `FOR APPROVAL: ${req.username} edited User ${updatedData.username}`
        : `${req.username} edited User ${updatedData.username}`,
      remarks
    );

    // Update scheduler if employee autoGenerated changed
    if (
      !needsApproval &&
      roleBaseNames.includes("employee") &&
      processedAutoGenerated
    ) {
      updateScheduler();
    }

    return res.status(201).json({
      message,
      data: needsApproval ? result.user : safeUser,
    });
  } catch (err) {
    console.log(err.message);
    return res.status(500).json({ error: err.message });
  }
};

// PUT me/
const editProfile = async (req, res) => {
  const { name, phone, email, description} = req.body;
  const newImage = req.file ? req.file.filename : null;

  try {
    let message;
    let existingUser;
    let pendingUser;

    const user = await prisma.user.findFirst({ where: { id: req.id } });

    if (email && email !== user.email) {
      existingUser = await prisma.user.findFirst({
        where: { email, id: { not: req.id }, status: "active", },
      });
      pendingUser = await checkPendingApproval(prisma, 'user', ['email'], email);
    }

    if (existingUser || pendingUser) {
      return res
        .status(400)
        .json({ message: "Email already in use or pending approval" });
    }

    let image = user.image;

    if (newImage) {
      if (user.image) {
        deleteFile(`images/${user.image}`);
      }
      image = newImage;
    }

    const updatedData = {
      fullName: name ?? user.fullName,
      username: user.username,
      phone: phone.toString() ?? user.phone,
      email: email ?? user.email,
      image: image ?? user.image,
      hashPwd: user.hashPwd,
      description: description ?? user.description,
      updatedByUser: req.username,
      image
    };

    const result = await prisma.$transaction(async (tx) => {
      const editedProfile = await tx.user.update({
        where: { id: user.id },
        data: updatedData,
      });

      message = "Profile edited successfully";

      return editedProfile;
    });

    await logActivity(
      req.username,
      `${req.username} edited User Profile ${updatedData.username}`,
    );

    return res.status(201).json({
      message,
      data: {
        ...(({ id, hashPwd, refreshToken, ...safeUser }) => safeUser)(result),
      },
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
};

// PUT me/password
const editProfilePassword = async (req, res) => {
  const { oldPassword, newPassword } = req.body;

  const user = await prisma.user.findFirst({ where: { id: req.id } });

  const isMatch = await bcrypt.compare(oldPassword, user.hashPwd);
  if (!isMatch) {
    return res.status(400).json({ message: "Invalid old password" });
  }

  const strongPasswordRegex =
    /^(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*])[A-Za-z\d!@#$%^&*]{8,}$/;

  if (!strongPasswordRegex.test(newPassword)) {
    return res.status(400).json({
      message:
        "Password must be at least 8 characters long, include an uppercase letter, a number, and a special character.",
    });
  }

  const hashPwd = await bcrypt.hash(newPassword, 10);

  const isUnchanged = await bcrypt.compare(oldPassword, hashPwd);
  if (isUnchanged) {
    return res
      .status(400)
      .json({ message: "New and old password cannot be the same" });
  }

  try {
    let message = "Profile password successfully changed";
    const updatedData = {
      fullName: user.fullName,
      username: user.username,
      phone: user.phone,
      email: user.email,
      hashPwd,
      description: user.description,
    };

    const result = await prisma.$transaction(async (tx) => {
      const editedProfilePassword = await tx.user.update({
        where: { id: user.id },
        data: updatedData,
      });
    });
    await logActivity(
      req.username,
      `${req.username} edited User ${updatedData.username}`,
    );

    return res.status(201).json({
      message,
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
};

// PUT /users/:id/password
const editUserPassword = async (req, res) => {
  const { newPassword } = req.body;

  if (!req?.params?.id) {
    return res.status(400).json({ message: "ID is required" });
  }

  const user = await prisma.user.findFirst({ where: { id: req.params.id } });
  if (!user) {
    return res
      .status(400)
      .json({ message: `User with ID ${req.params.id} doesn't exist` });
  }

  const strongPasswordRegex =
    /^(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*])[A-Za-z\d!@#$%^&*]{8,}$/;

  if (!strongPasswordRegex.test(newPassword)) {
    return res.status(400).json({
      message:
        "Password must be at least 8 characters long, include an uppercase letter, a number, and a special character.",
    });
  }

  const hashPwd = await bcrypt.hash(newPassword, 10);

  try {
    const needsApproval = req.approval;
    let message;

    const updatedData = {
      fullName: user.fullName,
      username: user.username,
      phone: user.phone,
      email: user.email,
      hashPwd,
      description: user.description,
    };

    const result = await prisma.$transaction(async (tx) => {
      const editedUserPassword = needsApproval
        ? await requestApproval('user', req.params.id, 'edit', {
              ...updatedData,
              createdByUser: req.username }, req.username)
        : await tx.user.update({
            where: { id: user.id },
            data: updatedData,
          });

      message = needsApproval
        ? "User password awaiting approval"
        : "User password successfully changed";
    });

    await logActivity(
      req.username,
      needsApproval
        ? `FOR APPROVAL: ${req.username} edited User Password ${updatedData.username}`
        : `${req.username} edited User Password ${updatedData.username}`
    );

    return res.status(201).json({
      message,
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
};

// DELETE /:id
const deleteUser = async (req, res) => {
  try {
    const needsApproval = req.approval;

    const user = await prisma.user.findUnique({
      where: { id: req.params.id },
      include: {
        admin: true,
        customer: {
          include: {
            trucks: true,
            jobOrders: true,
          },
        },
        contractor: {
          include: {
            contractorPay: true,
            jobOrders: true,
          },
        },
        employee: {
          include: {
            employeePay: true
          },
        },

        // exclude these from relation checking
        roles: true,
        branches: true,

        // keep all other created/updated relations
        activityLog: true,
        createdUsers: true,
        updatedUsers: true,
        createdRole: true,
        createdBranches: true,
        createdTrucks: true,
        createdTransactions: true,
        createdJobOrders: true,
        createdContractorPays: true,
        createdEquipments: true,
        createdOtherIncomes: true,
        createdOverheads: true,
        transferredTruckOwnerships: true,
        updatedBranches: true,
        updatedTrucks: true,
        updatedTransactions: true,
        updatedJobOrders: true,
        updatedContractorPays: true,
        updatedEquipments: true,
        updatedOtherIncomes: true,
        updatedOverheads: true,
      },
    });

    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    // 🔍 Check relations, but ignore roles/branches/edits
    const excludedKeys = ["roles", "branches"];
    const hasRelations = relationsChecker(user, excludedKeys);
    console.log(hasRelations)

    let message = hasRelations ? "User marked as inactive (has related records)" : "User deleted successfully"

    await logActivity(
      req.username,
      needsApproval
        ? `FOR APPROVAL: ${req.username} deleted User ${user.username}`
        : `${req.username} deleted User ${user.username}`
    );

    await prisma.$transaction(async (tx) => {

      if (needsApproval) {
        const approval = await requestApproval(
          "user",           // table name
          user.id,           // record id
          "delete",          // action type
          user,              // payload (snapshot of data)
          req.username        // requested by
        );

        return res.status(200).json({
          message: "User deletion pending approval",
          approvalId: approval.id, // include approval log ID here
        });
      }

      if (hasRelations) {
        await tx.user.update({
          where: { id: user.id },
          data: { status: "inactive", refreshToken: null, },
        });
      } else {
        // delete excluded relations first
        await tx.userRole.deleteMany({ where: { userId: user.id } });
        await tx.userBranch.deleteMany({ where: { userId: user.id } });

        await tx.customer.deleteMany({ where: { userId: user.id } });
        await tx.employee.deleteMany({ where: { userId: user.id } });
        await tx.contractor.deleteMany({ where: { userId: user.id } });
        await tx.admin.deleteMany({ where: { userId: user.id } });


        // finally delete the user
        await tx.user.delete({ where: { id: user.id } });
      }
    });

    
    updateScheduler();

    return res.status(200).json({ message });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
};

// GET /users
const getAllUsers = async (req, res) => {
  try {
    const role = req?.query?.role;
    const branch = req?.query?.branch;
    const search = req?.query?.search;
    const page = req?.query?.page && parseInt(req.query.page, 10);
    const limit = req?.query?.limit && parseInt(req.query.limit, 10);
    const startDate = req?.query?.startDate;
    const endDate = req?.query?.endDate;
    let totalItems = 0;
    let totalPages = 1;

    let where = { status: "active" };

    const createdAtFilter = getDateRangeFilter(startDate, endDate);
    if (createdAtFilter) {
      where.createdAt = createdAtFilter;
    }

    where = {...where, ...branchFilter("user", branch, req.branchIds)};

    //  Filter by role
    if (role) {
      where.roles = {
        some: {
          roleId: role, // since UserRole has roleId
        },
      };
    }

    if (branch) {
      let branchValue = req.query.branch.trim().replace(/^["']|["']$/g, "");
      where.branches = {
        some: {
          branch: {
            branchId: branchValue,
          },
        },
      };
    }

    //  Search filter
    if (search) {
      let searchValue = req.query.search.trim().replace(/^["']|["']$/g, "");

      where.OR = [
        { fullName: { contains: searchValue } },
        { username: { contains: searchValue } },
      ];
    }

    //  Query and pagination
    const result = await prisma.$transaction(async (tx) => {
      const users = await tx.user.findMany({
        where,
        ...(page && limit ? { skip: (page - 1) * limit } : {}),
        ...(limit ? { take: limit } : {}),
        orderBy: {
          createdAt: "desc",
        },
        include: {
          roles: { include: { role: true } },
          branches: { include: { branch: true } },
          contractor: { select: { commission: true } },
          employee: { select: { autoGenerated: true } },
        },
      });

      totalItems = await tx.user.count({ where });
      if (limit) totalPages = Math.ceil(totalItems / limit);

      // Exclude sensitive fields
      const formattedUsers = users.map((user) => {
        const { hashPwd, refreshToken, roles, branches, contractor, employee, ...safeUser } = user;

        return {
          ...safeUser,
          roles: roles.map((r) => ({
            id: r.role.id,
            roleName: r.role.roleName,
          })),
          branches: branches.map((b) => ({
            id: b.branch.id,
            branchName: b.branch.branchName,
          })),
          commission: Number(contractor?.commission) || undefined,
          autoGenerated: employee?.autoGenerated || undefined,
        };
      });

      return { users: formattedUsers };
    });

    res.status(200).json({
      data: { ...result, pagination: { totalItems, totalPages } },
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
};

// GET /:id
const getUser = async (req, res) => {
  if (!req?.params?.id)
    return res.status(400).json({ message: "ID is required" });

  try {
    const user = await prisma.user.findUnique({
      where: { id: req.params.id },
      include: {
        roles: { include: { role: true } },
        branches: { include: { branch: true } },
        contractor: true, // Direct relation without nested include
      },
    });

    if (!user) return res.status(404).json({ message: "User not found" });

    const { hashPwd, refreshToken, roles, branches, contractor, ...safeUser } =
      user;

    // Prepare response data
    const responseData = {
      ...safeUser,
      roles: roles.map((r) => ({
        id: r.role.id,
        roleName: r.role.roleName,
      })),
      branches: branches.map((b) => ({
        id: b.branch.id,
        branchName: b.branch.branchName,
      })),
    };

    // Add commission if contractor relation exists
    if (contractor) {
      responseData.commission = contractor.commission || null;
      // Add other contractor fields as needed
      // responseData.autoGenerated = contractor.autoGenerated || null;
    }

    return res.status(200).json({
      data: responseData,
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// GET /me
const getMyProfile = async (req, res) => {
  try {
    const user = await prisma.user.findUnique({
      where: { id: req.id },
      include: {
        roles: { select: { role: { select: { id: true, roleName: true } } } },
        branches: { select: { branch: { select: { id: true, branchName: true } } } },
      },
    });

    if (!user) return res.status(404).json({ message: "User not found" });

    const transformedUser = {
      ...user,
      roles: user.roles.map(r => r.role),
      branches: user.branches.map(b => b.branch),
    };

    const { hashPwd, refreshToken, ...safeUser } = transformedUser;

    res.status(200).json({
      data: {
        ...safeUser,
        // roles: roles.map((r) => r.role.roleName),
        // branches: branches.map((b) => b.branch.branchName),
      },
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

module.exports = {
  createUser,
  editUser,
  editProfile,
  editProfilePassword,
  getAllUsers,
  editUserPassword,
  deleteUser,
  getUser,
  getMyProfile
};
